---
- name: Install redmine dependencies
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - ImageMagick
    - ImageMagick-devel
    - python-pip
    - wget
    - libpqxx-devel
  become: yes

- name: Install psycopg2
  pip:
    name: psycopg2
    state: present
  become: yes

- name: Wait for postgres to be ready
  wait_for:
    port: 5432

- name: Create "{{ redmine_database_username }}" postgres user
  postgresql_user:
    name: "{{ redmine_database_username }}"
    password: "{{ redmine_database_password }}"
    encrypted: yes
  become: yes
  become_user: postgres

- name: Create "{{ redmine_database_name }}" database
  postgresql_db:
    name: "{{ redmine_database_name }}"
    encoding: UTF-8
    owner: "{{ redmine_database_username }}"
  become: yes
  become_user: postgres

- name: Copy ph_hba.conf to server
  copy:
    src: "{{ role_path }}/files/pg_hba.conf"
    dest: /var/lib/pgsql/10/data/pg_hba.conf
  become: yes

- name: Restart postgres
  systemd:
    name: postgresql-10
    state: restarted
  become: yes

- name: Install bundler and passenger
  gem:
    name: "{{ item }}"
    state: present
  with_items:
    - bundler
    - passenger
  become: yes
  become_user: "{{ redmine_system_user }}"
  environment:
    PATH: "/home/{{ redmine_system_user }}/.rvm/gems/ruby-{{ ruby_version }}/bin:/home/{{ redmine_system_user }}/.rvm/gems/ruby-{{ ruby_version }}@global/bin:/home/{{ redmine_system_user }}/.rvm/rubies/ruby-{{ ruby_version }}/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/{{ redmine_system_user }}/.rvm/bin:/home/{{ redmine_system_user }}/.local/bin:/home/{{ redmine_system_user }}/bin"
    GEM_PATH: "/home/{{ redmine_system_user }}/.rvm/gems/ruby-{{ ruby_version }}:/home/{{ redmine_system_user }}/.rvm/gems/ruby-{{ ruby_version }}@global"

- name: Give execute permission to redmine home directory
  shell: "chmod o+x /home/{{ redmine_system_user }}"
  become: yes

- name: "Download redmine and move to /home/{{ redmine_system_user }}/redmine"
  shell: "cd /home/{{ redmine_system_user }} && wget http://www.redmine.org/releases/redmine-3.4.4.tar.gz && tar -xf redmine-*.tar.gz && mv redmine-*/ redmine/"
  become: yes
  become_user: "{{ redmine_system_user }}"

- name: Copy configuration.yml to server
  copy:
    src: "{{ role_path }}/files/configuration.yml"
    dest: "/home/{{ redmine_system_user }}/redmine/config/configuration.yml"
  become: yes

- name: Copy database.yml to server
  template:
    src: "{{ role_path }}/templates/database.yml.j2"
    dest: "/home/{{ redmine_system_user }}/redmine/config/database.yml"
  become: yes

- name: Configure redmine database
  shell: "cd /home/{{ redmine_system_user }}/redmine && bundle config build.pg --with-pg-config=/usr/pgsql-10/bin/pg_config"
  become: yes
  become_user: "{{ redmine_system_user }}"
  environment:
    PATH: "/home/{{ redmine_system_user }}/.rvm/gems/ruby-{{ ruby_version }}/bin:/home/{{ redmine_system_user }}/.rvm/gems/ruby-{{ ruby_version }}@global/bin:/home/{{ redmine_system_user }}/.rvm/rubies/ruby-{{ ruby_version }}/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/{{ redmine_system_user }}/.rvm/bin:/home/{{ redmine_system_user }}/.local/bin:/home/{{ redmine_system_user }}/bin"
    GEM_PATH: "/home/{{ redmine_system_user }}/.rvm/gems/ruby-{{ ruby_version }}:/home/{{ redmine_system_user }}/.rvm/gems/ruby-{{ ruby_version }}@global"
  
- name: Install redmine gem dependencies
  shell: "cd /home/{{ redmine_system_user }}/redmine && bundle install --without development test"
  become: yes
  become_user: "{{ redmine_system_user }}"
  environment:
    PATH: "/home/{{ redmine_system_user }}/.rvm/gems/ruby-{{ ruby_version }}/bin:/home/{{ redmine_system_user }}/.rvm/gems/ruby-{{ ruby_version }}@global/bin:/home/{{ redmine_system_user }}/.rvm/rubies/ruby-{{ ruby_version }}/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/{{ redmine_system_user }}/.rvm/bin:/home/{{ redmine_system_user }}/.local/bin:/home/{{ redmine_system_user }}/bin"
    GEM_PATH: "/home/{{ redmine_system_user }}/.rvm/gems/ruby-{{ ruby_version }}:/home/{{ redmine_system_user }}/.rvm/gems/ruby-{{ ruby_version }}@global"

- name: Generate redmine session secrets
  shell: "cd /home/{{ redmine_system_user }}/redmine && bundle exec rake generate_secret_token"
  become: yes
  become_user: "{{ redmine_system_user }}"
  environment:
    PATH: "/home/{{ redmine_system_user }}/.rvm/gems/ruby-{{ ruby_version }}/bin:/home/{{ redmine_system_user }}/.rvm/gems/ruby-{{ ruby_version }}@global/bin:/home/{{ redmine_system_user }}/.rvm/rubies/ruby-{{ ruby_version }}/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/{{ redmine_system_user }}/.rvm/bin:/home/{{ redmine_system_user }}/.local/bin:/home/{{ redmine_system_user }}/bin"
    GEM_PATH: "/home/{{ redmine_system_user }}/.rvm/gems/ruby-{{ ruby_version }}:/home/{{ redmine_system_user }}/.rvm/gems/ruby-{{ ruby_version }}@global"

- name: Set up redmine postgres database
  shell: "cd /home/{{ redmine_system_user }}/redmine && RAILS_ENV=production bundle exec rake db:migrate"
  become: yes
  become_user: "{{ redmine_system_user }}"
  environment:
    PATH: "/home/{{ redmine_system_user }}/.rvm/gems/ruby-{{ ruby_version }}/bin:/home/{{ redmine_system_user }}/.rvm/gems/ruby-{{ ruby_version }}@global/bin:/home/{{ redmine_system_user }}/.rvm/rubies/ruby-{{ ruby_version }}/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/{{ redmine_system_user }}/.rvm/bin:/home/{{ redmine_system_user }}/.local/bin:/home/{{ redmine_system_user }}/bin"
    GEM_PATH: "/home/{{ redmine_system_user }}/.rvm/gems/ruby-{{ ruby_version }}:/home/{{ redmine_system_user }}/.rvm/gems/ruby-{{ ruby_version }}@global"

- name: Write redmine default data
  shell: "cd /home/{{ redmine_system_user }}/redmine && RAILS_ENV=production REDMINE_LANG=en bundle exec rake redmine:load_default_data"
  become: yes
  become_user: "{{ redmine_system_user }}"
  environment:
    PATH: "/home/{{ redmine_system_user }}/.rvm/gems/ruby-{{ ruby_version }}/bin:/home/{{ redmine_system_user }}/.rvm/gems/ruby-{{ ruby_version }}@global/bin:/home/{{ redmine_system_user }}/.rvm/rubies/ruby-{{ ruby_version }}/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/{{ redmine_system_user }}/.rvm/bin:/home/{{ redmine_system_user }}/.local/bin:/home/{{ redmine_system_user }}/bin"
    GEM_PATH: "/home/{{ redmine_system_user }}/.rvm/gems/ruby-{{ ruby_version }}:/home/{{ redmine_system_user }}/.rvm/gems/ruby-{{ ruby_version }}@global"

- name: Set up additional redmine directories
  shell: "cd /home/{{ redmine_system_user }}/redmine && mkdir -p tmp tmp/pdf public/plugin_assets && chown -R {{ redmine_system_user }}:{{ redmine_system_user }} files log tmp public/plugin_assets && chmod -R 755 files log tmp public/plugin_assets"
  become: yes